### ISSUE TITLE
Not enough arguments (missing: "opts").

### ISSUE THREAD

**Issue by DonMartio** [consolidation-org/Robo#366]
Hi there,

i have following task.

    /**
     * @param array $opts
     * @author mregner
     */
    public function adjust_config($opts = ['system|s' => 'local']) {

If i try to run it like this:
robo adjust_config -s test

[Symfony\Component\Console\Exception\RuntimeException]  
  Not enough arguments (missing: "opts").  

Robo version 1.0.0-beta1

If i omit the phpdoc it works. This is pretty weird.

**Comment by tomterl** [comment]
I took the time to dig a bit into this, and the problem seems to be that the `CommandDocBlockParser` (`consolidation\annotated-command`) does not see the default-value in the presence of an `@param` tag or something in that vain, and does not mark the parameter (symfony\InputArgument) as optional, so that symfony\console croaks if the command is called.

**Comment by greg-1-anderson** [comment]
`@param array opts` is telling Robo that your command is expecting an argument named $opts.  Use `@option string $system` instead.

Perhaps we should not override the meaning of @param like this -- folks might want to put in the phpdoc for completeness. @DavertMik?

**Comment by Sweetchuck** [comment]
I agree with that not to override the meaning of the @param.
A strict code linter can complain about the missing @param PhpDoc comment.

**Comment by tomterl** [comment]
So the only option we have is to not use `@param` tags in our robo-files? Our code-conventions don't allow this and we are hesitant to introduce exceptions to this rule;

**Comment by greg-1-anderson** [comment]
@tomterl: This was fixed in consolidation-org/annotated-command.  Now, @param has only its standard meaning; you may / should use it as intended -- to document the actual parameters of the method it was attached to.  I agree that the previous implementation was a bug.

Please try the 1.0.0-RC1 release, and provide feedback if you are still having problems with proper use of @param.

**Comment by tomterl** [comment]
@greg-1-anderson  Ok - cool -- many thanks for the clarification (and robo...)
