### ISSUE TITLE
Document how tasks should use `exec()` and other tasks from within their `run` method

### ISSUE THREAD

**Issue by borgogelli** [consolidation-org/Robo#370]
Hello
How can I create a task which can call the taskExec() method ?
The following code, show what I would like to do

class MyTask extends BaseTask { 

```
public function run(){
		$cmd = "echo Hello";
		$result = $this->taskExec($cmd)
		->printed(true)
		->run();
..........
	}

....
}
```

**Comment by greg-1-anderson** [comment]
`$this->taskExec()` and related `task` functions is only available to your primary Robo script.  We do not make BaseTask include `LoadAllTasks`, because then every task would be tightly bound to all of the core Robo tasks. We prefer to keep each task implementation isolated from the others as a general best-practice of writing testable / maintainable code.

If one task needs to run another task from its `run` method, then it should use `new` to instantiate and instance of any task that it needs.  Note that since Robo uses dependency injection, you need to call any necessary setter methods on your new task, to provide the logger object and anything else that it might need to run correctly.  To make setting up your subtasks easier, Robo provides a method called `inflect` that will automatically call the setter methods for you.  The way you use it is like this:
```
public function run()
{
    $cmd = "echo Hello";
    $exec = new Exec($cmd);
    $result = $exec->inflect($this)->printed(true)->run();
}
```
That's it.

Note, however, that if the subtask that you want to run is `Exec`, then you probably do not want to use a subtask at all. Instead, your can do this:
```
use \Robo\Common\ExecOneCommand;
public function run()
{
    $cmd = "echo Hello";
    $result = $this->executeCommand($cmd);
}
```
While neither of these options are terribly difficult, I realize that it is not entirely intuitive, since the execution model inside a task implementation is slightly different than the execution model in the primary Robo script model. Writing RoboFile scripts is the 90% use case, but you are correct that we need more complete documentation on writing tasks (specifically, techniques available when implementing the `run` method).  Additionally, I had an idea for how we could make things even easier to folks by providing a builder object that manages chaining of task creation, initialization and collections automatically.

Look for both of these things in the near future.

**Comment by greg-1-anderson** [comment]
If you have a task that is going to call a lot of other different kinds of tasks, and you do not mind having your class linked to all of the core Robo task classes, then you can simply add this to your task:
```
use ContainerAwareTrait;
use LoadAllTasks;
```
This will make `taskExec` and all of the other core tasks available in your task's methods.

**Comment by borgogelli** [comment]
Hi Greg
Thank you very much for that great piece of documentation which will be usefull to a lots of people besides me. Now I have only a last doubt: The following code is always needed when I want to link my custom external task, or I could load them in another better way ? 

```
$container = Robo\Config::getContainer();
$container->addServiceProvider(MyNameSpace\loadTasks::getMyServices());
```

(Using the MyNameSpace\loadTasks trait into the main Robo class, seem not sufficient for me. Am I wrong ?)

**Comment by greg-1-anderson** [comment]
You are correct; you must register your service providers as you show above, **and** use your loadTasks trait in your RoboFile.

Robo uses the League/Container dependency injection container. All tasks are registered in the container via a service manager. When some task (e.g. `taskFoo`) is referenced from your namespace, then it calls through to the `task` method of the TaskAccessor trait, which fetches it from the DI container.  This allows for the dependencies of each task to be injected when the task instance is created.

This should be documented as well.

**Comment by greg-1-anderson** [comment]
One simplification, though: your RoboFile should always extend Robo\Tasks, which is a ContainerAwareInterface.  Therefore, you may use `$this->getContainer()` like so:
```
$this->getContainer()->addServiceProvider(MyNameSpace\loadTasks::getMyServices());
```

**Comment by greg-1-anderson** [comment]
This actually is documented in [Tasks](http://robo.li/getting-started/#tasks), although the docs are vague where this code is to go. Presently, all of your commands would have to call an initializer function, if you have more than one command; perhaps Robo should provide this service, and define an initialize() method in `Tasks`.

**Comment by geek-merlin** [comment]
Search engines brought me here, so FTR:
Today simply use task getter trains like so:
```
  use \Robo\Task\Composer\Tasks;
  use \Robo\Task\File\Tasks;
  use \Robo\Task\Filesystem\Tasks;
  use \Robo\Task\Filesystem\Shortcuts;

```
